from btree import BTree
if __name__ == "__main__":
    tree = BTree(2)

    tree.insert_key(20)
    tree.insert_key(10)
    tree.insert_key(40)
    tree.insert_key(50)
    tree.insert_key(30)
    tree.print_tree()
    
    # tree.insert_key(55)
    # tree.insert_key(3)    
    # tree.insert_key(11)
    # tree.insert_key(4)

    # tree.insert_key(28)
    # tree.print_tree()
    # tree.insert_key(36)
    # tree.print_tree()
    # tree.insert_key(33)
    # tree.print_tree()
    # tree.insert_key(52)
    # tree.print_tree()
    # tree.insert_key(17)
    # tree.print_tree()
    # tree.insert_key(25)
    # tree.print_tree()
    # tree.insert_key(13)
    # tree.print_tree()
    # tree.insert_key(45)
    # tree.print_tree()
    # tree.insert_key(9)
    # tree.print_tree()
    # tree.insert_key(43)
    # tree.print_tree()
    # tree.insert_key(8)
    # tree.print_tree()
    # tree.insert_key(48)
    #tree.print_tree()